# Generated by Django 3.1.5 on 2021-01-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210120_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsubscription',
            old_name='event',
            new_name='events',
        ),
    ]
