# Generated by Django 3.1.5 on 2021-01-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210120_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='eventsubscription',
            old_name='user',
            new_name='participant',
        ),
    ]
