# Generated by Django 3.1.5 on 2021-01-20 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20210120_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubscription',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
