# Generated by Django 3.1.5 on 2021-01-20 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20210120_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventSubscription',
            new_name='EventSubscribtion',
        ),
    ]
