# Generated by Django 3.1.5 on 2021-01-22 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210122_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 9, 2, 38, 843750, tzinfo=utc)),
        ),
    ]
