# Generated by Django 3.1.5 on 2021-01-22 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210122_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 9, 12, 2, 727683, tzinfo=utc)),
        ),
    ]
